### ISSUE TITLE
CreateDriverCallSignature

### ISSUE THREAD

**Issue by ImProta** [felixschurk/sisc-lab#15]
# Properly define the full Driver Call Signature:
The input are the call signature, active variables and driver type
```YAML
call_signature: void f(std::vector<double> &x)   
active variables: x
driver_type: jacobian
```
Consider the driver type to define the input variables and its type

# Output
```cpp
void f_jacobian(std::vector<double> &x, std::vector<std::vector<double>> &dx)  
std::vector<double> x_t(x.size(), 0.0);
```
